UPDATE autocomDB.Program SET p_category = 'design', p_os = 'windows', p_cpu = 'ryzen5-5600x', p_vga = 'geforcertx3050', p_ram = 8, p_ssd = 500 WHERE p_name = '3ds max';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'all', p_cpu = 'i5-11400', p_vga = null, p_ram = 8, p_ssd = 1000 WHERE p_name = 'ableton live';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'all', p_cpu = 'i3-10100', p_vga = null, p_ram = 8, p_ssd = 1000 WHERE p_name = 'android studio';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'windows', p_cpu = 'ryzen5-5600x', p_vga = null, p_ram = 16, p_ssd = 1000 WHERE p_name = 'ansys fluent';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'all', p_cpu = 'i5-12400f', p_vga = 'geforcertx3060ti', p_ram = 8, p_ssd = 1000 WHERE p_name = 'archicad';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 500 WHERE p_name = 'audacity';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 500 WHERE p_name = 'auduiotool';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'all', p_cpu = 'ryzen5-5600x', p_vga = 'geforcertx2060', p_ram = 16, p_ssd = 1000 WHERE p_name = 'autocad';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'windows', p_cpu = 'i3-10320', p_vga = null, p_ram = 8, p_ssd = 500 WHERE p_name = 'bandlab';
UPDATE autocomDB.Program SET p_category = 'design', p_os = 'all', p_cpu = 'ryzen7-5800', p_vga = 'geforcertx3060ti', p_ram = 16, p_ssd = 500 WHERE p_name = 'blender';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'windows', p_cpu = 'i3-12100f', p_vga = 'geforcegtx1650super', p_ram = 16, p_ssd = 500 WHERE p_name = 'cakewalk sonar';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'windows', p_cpu = 'i7-12700f', p_vga = 'geforcertx3060ti', p_ram = 16, p_ssd = 500 WHERE p_name = 'catia';
UPDATE autocomDB.Program SET p_category = 'video', p_os = 'all', p_cpu = 'i5-10400f', p_vga = 'geforcertx2060', p_ram = 16, p_ssd = 1000 WHERE p_name = 'cinema4d';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 500 WHERE p_name = 'clion';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'windows', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 8, p_ssd = 500 WHERE p_name = 'creo';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'all', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 8, p_ssd = 1000 WHERE p_name = 'cubase';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'windows', p_cpu = 'i3-8100', p_vga = null, p_ram = 4, p_ssd = 500 WHERE p_name = 'docker';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 500 WHERE p_name = 'eclipse';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'windows', p_cpu = 'i3-8100', p_vga = 'geforcegtx1660', p_ram = 8, p_ssd = 500 WHERE p_name = 'enscape';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'all', p_cpu = 'i5-10400', p_vga = null, p_ram = 16, p_ssd = 1000 WHERE p_name = 'fl studio';
UPDATE autocomDB.Program SET p_category = 'design', p_os = 'all', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 16, p_ssd = 500 WHERE p_name = 'illustrator';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'windows', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 500 WHERE p_name = 'intellij';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'windows', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 32, p_ssd = 500 WHERE p_name = 'inventor';
UPDATE autocomDB.Program SET p_category = 'design', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 4, p_ssd = 1000 WHERE p_name = 'keyshot';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 4, p_ssd = 500 WHERE p_name = 'lmms';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'mac', p_cpu = 'm1', p_vga = 'm1', p_ram = 16, p_ssd = 1000 WHERE p_name = 'logic pro';
UPDATE autocomDB.Program SET p_category = 'design', p_os = 'windows', p_cpu = 'i3-9100', p_vga = 'geforcertx2070super', p_ram = 32, p_ssd = 500 WHERE p_name = 'lumion';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'all', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 4, p_ssd = 500 WHERE p_name = 'matlab';
UPDATE autocomDB.Program SET p_category = 'design', p_os = 'all', p_cpu = 'i5-10400f', p_vga = 'geforcegtx1650super', p_ram = 16, p_ssd = 1000 WHERE p_name = 'maya';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 4, p_ssd = 500 WHERE p_name = 'mysql workbench';
UPDATE autocomDB.Program SET p_category = 'photos', p_os = 'all', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 16, p_ssd = 1000 WHERE p_name = 'photoshop';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'all', p_cpu = 'i5-10400', p_vga = null, p_ram = 8, p_ssd = 1000 WHERE p_name = 'protools';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'windows', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 500 WHERE p_name = 'pycharm';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 4, p_ssd = 500 WHERE p_name = 'r studio';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'windows', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 500 WHERE p_name = 'revit';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'all', p_cpu = 'i5-10400f', p_vga = 'geforcegtx1650super', p_ram = 8, p_ssd = 500 WHERE p_name = 'rhino';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'all', p_cpu = 'i5-10400f', p_vga = 'geforcegtx1650super', p_ram = 4, p_ssd = 500 WHERE p_name = 'ros';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 500 WHERE p_name = 'simulink';
UPDATE autocomDB.Program SET p_category = 'design', p_os = 'all', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 8, p_ssd = 1000 WHERE p_name = 'sketchup';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 16, p_ssd = 500 WHERE p_name = 'solidworks';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'windows', p_cpu = 'i5-10400f', p_vga = null, p_ram = 16, p_ssd = 1000 WHERE p_name = 'soundation';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 1000 WHERE p_name = 'spyder';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 4, p_ssd = 500 WHERE p_name = 'sql developer';
UPDATE autocomDB.Program SET p_category = 'music', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 1000 WHERE p_name = 'studio one';
UPDATE autocomDB.Program SET p_category = 'design', p_os = 'all', p_cpu = 'i7-10700', p_vga = 'geforcertx2080super', p_ram = 16, p_ssd = 1000 WHERE p_name = 'substance designer';
UPDATE autocomDB.Program SET p_category = 'design', p_os = 'all', p_cpu = 'i7-10700', p_vga = 'geforcertx2080super', p_ram = 16, p_ssd = 1000 WHERE p_name = 'substance painter';
UPDATE autocomDB.Program SET p_category = 'productivity', p_os = 'windows', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 16, p_ssd = 1000 WHERE p_name = 'twinmotion';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'all', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 8, p_ssd = 500 WHERE p_name = 'unity';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'all', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 8, p_ssd = 500 WHERE p_name = 'unreal engine';
UPDATE autocomDB.Program SET p_category = 'design', p_os = 'all', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 16, p_ssd = 1000 WHERE p_name = 'v-ray';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'all', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 500 WHERE p_name = 'visual studio';
UPDATE autocomDB.Program SET p_category = 'developers', p_os = 'windows', p_cpu = 'i3-8100', p_vga = null, p_ram = 8, p_ssd = 500 WHERE p_name = 'webstorm';
UPDATE autocomDB.Program SET p_category = 'design', p_os = 'windows', p_cpu = 'i3-8100', p_vga = 'geforcegtx1650super', p_ram = 8, p_ssd = 1000 WHERE p_name = 'zbrush';
