create table Major
(
    m_name     varchar(30) not null,
    m_category varchar(30) null,
    m_prog     varchar(30) not null
);

INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'autocad');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'photoshop');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'revit');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'sketchup');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'rhino');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'archicad');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'v-ray');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'lumion');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'twinmotion');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'enscape');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'keyshot');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('건축공학과', '공학계열', 'illustrator');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('고분자공학과', '공학계열', 'matlab');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('기계공학과', '공학계열', 'autocad');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('기계공학과', '공학계열', 'ansys fluent');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('기계공학과', '공학계열', 'inventer');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('기계공학과', '공학계열', 'simulink');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('기계공학과', '공학계열', 'ros');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('기계공학과', '공학계열', 'catia');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('기계공학과', '공학계열', 'solidworks');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('기계공학과', '공학계열', 'matlab');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('기계설계공학과', '공학계열', 'autocad');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('기계설계공학과', '공학계열', 'creo');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('기계설계공학과', '공학계열', 'ansys');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'visual studio');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'intellij');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'eclipse');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'r studio');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'android studio');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'pycharm');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'spyder');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'unity');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'docker');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'clion');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'webstorm');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('컴퓨터공학과', '공학계열', 'mysql workbench');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('산업디자인학과', '예체능계열', '3ds max');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('산업디자인학과', '예체능계열', 'rhino');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('산업디자인학과', '예체능계열', 'photoshop');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('산업디자인학과', '예체능계열', 'illustrator');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('산업디자인학과', '예체능계열', 'maya');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('산업디자인학과', '예체능계열', 'blender');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('산업디자인학과', '예체능계열', 'unreal engine');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('산업디자인학과', '예체능계열', 'unity');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('화학공학과', '공학계열', 'matlab');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', '3ds max');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'zbrush');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'substance painter');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'substance designer');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'rhino');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'keyshot');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'v-ray');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'autocad');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'solidworks');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'catia');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'sketchup');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'maya');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'cinema4d');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'illustrator');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('시각디자인학과', '예체능계열', 'photoshop');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'cubase');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'logic pro');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'ableton live');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'bandlab');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'lmms');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'cakewalk sonar');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'studio one');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'soundation');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'auduiotool');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'audacity');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'protools');
INSERT INTO autocomDB.Major (m_name, m_category, m_prog) VALUES ('실용음악학과', '예체능계열', 'fl studio');